blog/urls.py
from django.urls import path,include,re_path
from . import views
app_name = "blog"
urlpatterns = [
    path("blogs", views.blogs, name="blogs"),
    path("add_blogs", views.add_blogs, name="add_blogs"),
    path('<slug:slug>/blog-comments', views.blog_comments, name="blog_comments"),
    #re_path(r'^join/', views.join, name='join'),
]

homepage/urls.py
from django.urls import path
from .views import PostCreateView,PostDetailView
from . import views
app_name = "homepage"
urlpatterns = [
    path("",views.index, name="index"),
    path('post/new/', PostCreateView.as_view(), name='new_post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('join_hood/<int:pk>/', views.joinHood, name='join_hood'),
    path('delete_post/<int:pk>/', views.deletePost, name='delete_post'),
    path('create_business/<int:pk>/', views.createBusiness, name='create_business')
    #path('post/<int:pk>/', views.detailView,name="post-detail"),
]

neighborhood/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls", namespace="homepage")),
    path("", include("users.urls", namespace="users")),
    path("", include("blog.urls", namespace="blog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]
##development media and static files settings
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)
    
if settings.DEBUG:
    urlpatterns+= static(
    settings.STATIC_URL, 
    document_root = settings.STATIC_ROOT)   

blog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.timezone import now
# Create your models here.
class BlogPost(models.Model):
    title=models.CharField(max_length=255)
    author= models.ForeignKey(User, on_delete=models.CASCADE)
    slug=models.CharField(max_length=130)
   
    content=models.TextField()
    image = models.ImageField(upload_to="blog_pics", blank=True, null=True)
    dateTime=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return str(self.author) +  " Blog Title: " + self.title
    
    def get_absolute_url(self):
        return reverse('blogs')

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)   
    dateTime=models.DateTimeField(default=now)
 
    def __str__(self):
        return self.user.username +  " Comment: " + self.content

blog/forms.py
from django import forms  
from django.contrib.auth.models import User  
from .models import BlogPost,Comment
class BlogPostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ('title', 'slug', 'content', 'image')
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Title of the Blog'}),
            'slug': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Copy the title with no space and a hyphen in between'}),
            'content': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Content of the Blog'}),
        }

blog/views.py
from django.shortcuts import render,redirect
from .models import BlogPost,Comment
from .forms import BlogPostForm
# Create your views here.
def blogs(request):
    posts = BlogPost.objects.all()
    posts = BlogPost.objects.filter().order_by('-dateTime')
    return render(request, "blog.html", {'posts':posts})

def add_blogs(request):
    if request.method=="POST":
        form = BlogPostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            blogpost = form.save(commit=False)
            blogpost.author = request.user
            blogpost.save()
            obj = form.instance
            alert = True
            return redirect('blog:blogs')  
    else:
        form=BlogPostForm()
    return render(request, "add_blogs.html", {'form':form})


def blogs_comments(request, id):
    post = BlogPost.objects.get(id = id)
    return render(request, "blog_comments.html", {'post':post}) 

def blog_comments(request, slug):
    post = BlogPost.objects.filter(slug=slug).first()
    comments = Comment.objects.filter(blog=post)
    if request.method=="POST":
        user = request.user
        content = request.POST.get('content','')
        blog_id =request.POST.get('blog_id','')
        comment = Comment(user = user, content = content, blog=post)
        comment.save()
    return render(request, "blog_comments.html", {'post':post, 'comments':comments}) 

blog/templates/add_blogs.html
{% extends "base.html" %}
{% block content %}
<body style="background-color: wheat !important;">
<form action="" enctype="multipart/form-data" method="POST"> {% csrf_token %}
    <div class="container mt-4">
    {{ form.as_p }}
    <button class="btn btn-primary">Add Business</button>
    </div>
    </form>
    </body>
    {% endblock %}

blog/templates/blog.html
{% extends "base.html" %}
{% block content %}
<div class="navbar">
    {% include "home/navbar.html" %}
</div>
<body style="background-color: wheat !important;">


<h3>Bussinesses</h3>
  <div class="container-fluid mt-5">
    <div class="px-lg-5">
      <div class="row">
        <!-- Gallery item -->
        {%for post in posts%}
        <div class="col-xl-4 col-lg-3 col-md-4 mb-4">
         
          <div class="bg-white rounded shadow-sm">
            {{post.name}}
            <a href="/project/{{project.id}}">
              <img
                src="/media/{{post.image}}"
                alt=""
                class="img-fluid card-img-top"
              />
            </a>
            <div class="p-4">
              <h5><a href="#" class="text-dark"> {{ post.title }}<br> 
             
              </p></a></h5>
              <p class="small text-muted mb-0">
                {{post.content| truncatechars:210}}
              </p>

              <div class="container">
                <div class="row row-cols-2">
                  <div class="col"> <a href="{% url 'blog:blog_comments' post.slug %}" class="btn btn-primary">Read More </a><br></div>
                  <div class="col">
                    <a href="{% url 'homepage:delete_post' post.id %}" class="btn btn-danger">Delete Blog</a></a>
                  </div>
                  <div class="col"></div>
                  <div class="col"></div>
                </div>
              </div>



               </a></p><br>
             
                 <small style="opacity: 0.8; " >
                  Added on: {{ post.dateTime | date:"H:i l, d.m.y" }} 
                  <hr>by {{post.author}}
               </small>
              <div
                class="
                  d-flex
                  align-items-center
                  justify-content-between
                  rounded-pill
                  px-3
                  py-2
                  mt-4
                "
              >
                <p class="small mb-0">
                
                  <span class="font-weight-bold"></span>
                </p>
                <div
                  class="badge badge-primary px-3 rounded-pill font-weight-normal"
                ></div>
                <div
                  class="badge badge-success px-3 rounded-pill font-weight-normal"
                ></div>
              </div>
            </div>
          </div>
        </div>
        {%endfor%}
        <!-- End -->
      </div>
    </div>
  </div>






  
      </div>
    </div>
  </body>
  {% endblock %}

blog/templates/blog_comments.html
{% extends "base.html" %}
{% block content %}
<body style="background-color: wheat !important;">
<div class="container">
    <div class="row row-cols-2">
      <div class="col">
        <div class="container w-75 my-4">
            <h2 class="blog-post-title">{{post.title}}</h2>
            <br>
            <div class="media">
                  {% if post.author.profile.image %}
                  <img class="mr-3 rounded-circle" src="{{post.author.profile.image.url}}" width="50px" height="50px"
                        alt="image">
                  {% endif %}
                  <div class="media-body">
                        <h5 class="mt-0"><a href="/user_profile/{{post.author.id}}/">{{post.author}}
                                    {% if user.is_authenticated %}
                                    {% if user.id == post.author.id %}
                                    <small style="margin-left: 1rem;"><a href="" class="edit btn btn-warning">Back to my hood</a></small><hr>
                                    <small style="margin-left: 6.5rem;"><a href="/edit_blog_post/{{post.slug}}/" class="edit btn btn-warning">Edit Blog Post</a></small>
                                    {% endif %}
                                    {% endif %}
                              </a></h5>
                        {{post.dateTime}}
                  </div>
            </div>
            <br>
            <img src="/media/{{post.image}}" alt="" height="250px" width="500px">
            <br>
            <p>{{post.content}}.</p>
            <hr>
            {% if user.is_authenticated %}
            <div class="container">
                  <h2>Add Comments Here</h2>
                  <form action="" method="POST"> {% csrf_token %}
                        <div class="form-floating">
                              <textarea class="form-control" placeholder="Leave a comment here" id="floatingTextarea2"
                                    style="height: 100px" id="content" name="content"></textarea>
                              <label for="floatingTextarea2">Leave a comment here.</label>
                              <br>
                              <button type="submit" class="btn btn-primary">Comment</button>
                        </div>
                  </form>
                  {% else %}
                  <div class="container">
                        <h4><a href="/login/">Login</a> to post comments below.</h4>
                        {% endif %}
                        <br>
                        <h2>All Comments ({{comments.count}})</h2>
                        <br>
                     
                  </div>
            </div>
      </div>
      <div class="col" style="margin-top: 3rem;">  <center><p>Comments</p></center>
            {% for comment in comments %}
     
        <div class="card" style="margin-left: 5rem;">
           
              <div class="card-header">
                    <span style="font-size: 14px;">{{comment.user}} </span> <span
                    >
              </div>
              <div class="card-body">
                    <h6 class="card-text">{{comment.content}}</h6>
              </div>
        </div>
        <br>
        {% endfor %}</div>
      <div class="col"></div>
      <div class="col"></div>
    </div>
  </div>
</body>
{% endblock %}