blog/urls.py
from django.urls import path,include,re_path
from . import views
app_name = "blog"
urlpatterns = [
    path("blogs", views.blogs, name="blogs"),
    path("add_blogs", views.add_blogs, name="add_blogs"),
    path('<slug:slug>/blog-comments', views.blog_comments, name="blog_comments"),
    #re_path(r'^join/', views.join, name='join'),
]

homepage/urls.py
from django.urls import path
from .views import PostCreateView,PostDetailView
from . import views
app_name = "homepage"
urlpatterns = [
    path("",views.index, name="index"),
    path('post/new/', PostCreateView.as_view(), name='new_post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('join_hood/<int:pk>/', views.joinHood, name='join_hood'),
    path('delete_post/<int:pk>/', views.deletePost, name='delete_post'),
    path('create_business/<int:pk>/', views.createBusiness, name='create_business')
    #path('post/<int:pk>/', views.detailView,name="post-detail"),
]

neighborhood/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls", namespace="homepage")),
    path("", include("users.urls", namespace="users")),
    path("", include("blog.urls", namespace="blog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]
##development media and static files settings
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)
    
if settings.DEBUG:
    urlpatterns+= static(
    settings.STATIC_URL, 
    document_root = settings.STATIC_ROOT)   

homepage/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse
from cloudinary.models import CloudinaryField
class Location(models.Model):
    name = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    """
    Post model class to define post database table
    """
    name = models.CharField(max_length=400)
    location = models.ForeignKey('Location',null=True, on_delete=models.CASCADE)
      #image field
    image = CloudinaryField('image')
    #image = models.ImageField(upload_to='uploads/')
    description = models.CharField(max_length=100, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    occupants = models.ManyToManyField(User, related_name='occupants', blank=True)
    fire_department = models.IntegerField(null=True)
    hospital_contact = models.IntegerField(null=True)
    security_department = models.IntegerField(null=True)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('homepage:index')
    
    @property
    def number_of_comments(self):
        return Comment.objects.filter(post=self).count()

class Business(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    neighborhood = models.ForeignKey(Post, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    phone = models.IntegerField()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name 

homepage/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User  
from .models import Business
class BusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ['name', 'email','phone']

homepage/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from blog.models import BlogPost,Comment
from blog.forms import BlogPostForm
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required 
# Create your views here.
def index(request):
    context = {
        'posts':Post.objects.all()
    }
    return render(request, "home/index.html", context)


class PostCreateView(LoginRequiredMixin, CreateView):
    """
    view class to create post
    """
    model = Post
    fields = "__all__"
    template_name = 'hoods/create_hood.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


@login_required(login_url='/accounts/login/')
def post(request, pk):
    """
    View to handle post model
    Args:
    Pk - Primary Key,an unique way to identify an object uniquely in relational database systems
    """

    post = Post.objects.get(pk=pk)
    user = request.user
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(author= user,description=form.cleaned_data["description"],post=post)
            comment.save()

    comments = Comment.objects.filter(post=post).order_by('-date_posted')
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
   
    return self.get(self, request, pk, context)

class PostDetailView(DetailView):
    model = Post
    template_name = 'hoods/hood.html'
    context_object_name = 'post'

def joinHood(request,pk):
    hood =  Post.objects.get(id=pk)
    hood.occupants.add(request.user)
    occupants = hood.occupants.all()

    context = {
       'hood':hood,
       'occupants':occupants 
    }
    return render(request, 'hoods/hood.html', context)

@login_required(login_url='login')
def deletePost(request, pk):
    post = BlogPost.objects.get(id=pk)

    if request.user != post.author:
        return HttpResponse('You are not allowed')

    if request.method == 'POST':
        post.delete()
        return redirect('homepage:index')
    context = {

    }
    return render(request, 'hoods/delete.html', {'obj':post})


@login_required(login_url='login')
def createBusiness(request, pk):
    hood = Post.objects.get(id=pk)
    form = BusinessForm()
    user = request.user

    if request.method == 'POST':
        business = Business.objects.create (
            owner = user,
            neighborhood = hood,
            name = request.POST.get('name'),
            email= request.POST.get('email'),
            phone = request.POST.get('phone'),

        )
        return redirect('homepage:post-detail', pk=hood.id)     
    context = {
        'form':form,
        'hood': hood
    }
    return render(request, 'hoods/create_bussiness.html', context)

@login_required(login_url='login')
def search_profile(request):
    if 'search_user' in request.GET and request.GET['search_user']:
        name = request.GET.get("search_user")
        results = Profile.search_profile(name)
        print(results)
        message = f'name'
        params = {
            'results': results,
            'message': message
        }
        return render(request, 'results.html', params)
    else:
        message = "You haven't searched for any  category"
    return render(request, 'results.html', {'message': message})

homepage/templates/hoods/create_bussiness.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block content %} 
<body style="background-color: wheat !important;">
<div class="form-wrapper my-3">
    <h3>create business</h3>
    <form action="" method='post'>
        {% csrf_token %}  
        {% bootstrap_form form %}        
        <!-- {{ form.as_p }} -->
        <input type="submit" value="create business" class="create-btn">
    </form>   
</div>
</body>
{% endblock %}

homepage/templates/hoods/create_hood.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    body {
        background-image: urlhttps://unsplash.com/photos/OWexi1sNXQw;
        
    }
    .card {
        border: 2px solid black;
      
    }
</style>
<center><div class="container" style="margin-top: 5rem; width: 100;">
    <div class="card" style="width: 150;">
    <div class="text-center">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
          
            <fieldset class="form-group" >Add Your Hood here<br><br><hr>
               <div class="form-group">{{ form | crispy }}</div>
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="margin: 2rem;">Add</button>
            </div>
        </form></div></div></div></center>
    </div>
    
    {% endblock %}

homepage/templates/hoods/delete.html
{% extends 'base.html' %} 


{% block content %} 

    <form action="" method="POST">
        {% csrf_token %}
        <p>Are you sure you want that you want to delete "{{obj}}"?</p>
        <a href="{{ request.META.HTTP_REFERER }}">go back</a>
        <input type="submit" value='confirm'>
    </form>

{% endblock %}

homepage/templates/hoods/hood.html
{% extends "base.html" %} 
{% block content %}

<body style="background-color: wheat !important;">

<div class="container">

    <div class="row row-cols-2">
      <div class="col">
        <div class="container">
            <h3 class="white-important mb-3">
            Hood: {{post.location}}
            </h3>
            <article class="media content-section">
              <div style="width: 100%; word-break: break-all;" class="hovered-tweet-comment">
                <div class="pb-2 row m-0 " style="width: 100%; margin-right: 0 !important;">
                  <div style="padding-left: 0px !important;" class="col-8 no-padding d-flex align-items-center">
                    <img class="rounded-circle mr-2" style="width: 20px; height: 20px;" src="{{ post.author.profile.image.url }}">
                    {{ post.author }}
                  </div>
                  <div class="col-4 d-flex flex-row-reverse no-padding align-items-center" style="padding-right: 0 !important;">
                    {% if post.author == user %}
                    <div class="row">
          
                    </div>
                    {%  endif %}
                  </div>
                </div>
                <div class="mb-2 " style="width: 100%;">
                  <a>
                    <img class="card-img-top" class="img-responsive" src="{{post.image.url}}" size="100px200"><br>
                    <p>
                      <center>{{ post.description }}</center>
                    </p>
                    <br>
                  
                    <br>
                    
                    <small class="white-important d-flex full-width flex-row-reverse">
                      {{ post.date_posted | date:"H:i l, d.m.y" }}
                    </small>
                  
                  </a>
                </div>
            </article>
           
          </div>
          
         
      </div>
      <div class="col" style="margin-top: 6rem;">
        <button type="button" class="btn btn-primary">Join  this neighbourhood</button>
        <button type="button" class="btn btn-danger">Leave this neighbourhood</button>
        <div class="container" style="margin-top: 3rem;">
          <div class="row row-cols-2">
            <div class="col">
            
             
            </div>
            <div class="col"></div>
            <div class="col">
              <img src="https://media.istockphoto.com/photos/american-policeman-and-police-car-in-the-background-picture-id1249400249?b=1&k=20&m=1249400249&s=170667a&w=0&h=W9ISZ_KUSX5ZlYhgDbDchudq4CvGAxkuhbP8V3J61iM=" width="150" height="150">
              <p>Police  and inteligence Information</p>
              {{post.security_department}}
            
            </div>
            <div class="col">
              <img src="https://media.istockphoto.com/photos/modern-hospital-building-picture-id1312706504?b=1&k=20&m=1312706504&s=170667a&w=0&h=IcYI9Pm-s-JyeCOgul1DfSQAqY3hVte4uXnStOXbkaw=" width="150" height="150">
              <p>Hospitals</p>
              {{post.hospital_contact}}
              {% for business in context %} 
              {{business.name}}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      <div class="col">
        <a style="margin-left: 0rem;" href="{% url 'blog:add_blogs' %}" class="btn btn-primary" role="button">Add  your ownBusiness</a>
        <a style="margin-left: 6rem;" href="{% url 'blog:blogs' %}" class="btn btn-primary" role="button">View Businesses that are available</a>
        
      </div>
      <div class="col"></div>
    </div>
  </div>

  </html>
{% endblock %}