blog/urls.py
from django.urls import path,include,re_path
from . import views
app_name = "blog"
urlpatterns = [
    path("blogs", views.blogs, name="blogs"),
    path("add_blogs", views.add_blogs, name="add_blogs"),
    path('<slug:slug>/blog-comments', views.blog_comments, name="blog_comments"),
    #re_path(r'^join/', views.join, name='join'),
]

homepage/urls.py
from django.urls import path
from .views import PostCreateView,PostDetailView
from . import views
app_name = "homepage"
urlpatterns = [
    path("",views.index, name="index"),
    path('post/new/', PostCreateView.as_view(), name='new_post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('join_hood/<int:pk>/', views.joinHood, name='join_hood'),
    path('delete_post/<int:pk>/', views.deletePost, name='delete_post'),
    path('create_business/<int:pk>/', views.createBusiness, name='create_business')
    #path('post/<int:pk>/', views.detailView,name="post-detail"),
]

neighborhood/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls", namespace="homepage")),
    path("", include("users.urls", namespace="users")),
    path("", include("blog.urls", namespace="blog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]
##development media and static files settings
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)
    
if settings.DEBUG:
    urlpatterns+= static(
    settings.STATIC_URL, 
    document_root = settings.STATIC_ROOT)   

users/urls.py
from django.urls import path,include,re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"   


urlpatterns = [
    path('api/profile',views.ProfileList.as_view()),
    path('profile/',views.profile,name = 'profile'),
    #path('user_profile/',views.user_profile,name = 'user_profile'),
    path('edit_profile/',views.edit_profile,name = 'edit_profile'), 
    path("/", views.register, name="register"),
    #path('profile/',views.profile,name = 'profile'),

    

]

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    """[Profile]

    Args:
        models ([ModelClass]): [Profile model to create a user profile]

    Returns:
        [models.model]: [model class to be able to use all its properties and mine]
    """
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='profile_images')
    user_bio = models.CharField(max_length=30)
    date_created= models.DateField(auto_now_add=True )

    def __str__(self):
        return self.user.username
 
    def save_profile(self):
        self.user

    def delete_profile(self):
        self.delete()    

    @classmethod
    def search_profile(cls, name):
        return cls.objects.filter(user__username__icontains=name).all()
    
  

users/forms.py
from django import forms  
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm  
from django.core.exceptions import ValidationError  
from django.forms.fields import EmailField  
from django.forms.forms import Form  
from .models import Profile
class CustomUserCreationForm(UserCreationForm):  
    username = forms.CharField(label='username', min_length=5, max_length=150)  
    email = forms.EmailField(label='email', widget=forms.TextInput(attrs={"class":"form-control"}))  
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)  
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)  

    #widgets
    username.widget.attrs.update({'class': 'form-control'})
    password1.widget.attrs.update({'class': 'form-control'})
    password2.widget.attrs.update({'class': 'form-control'})

    def username_clean(self):  
        username = self.cleaned_data['username'].lower()  
        new = User.objects.filter(username = username)  
        if new.count():  
            raise ValidationError("User Already Exist")  
        return username  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError(" Email Already Exist")  
        return email  
  
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Password don't match")  
        return password2  
  
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']  
        )  
        return user 


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','email'] 

class UpdateUserProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user_bio', 'photo']

class profileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = [ 'photo', 'user_bio']

users/views.py
from django.contrib.auth import login
from django.shortcuts import redirect, render,get_object_or_404
from django.urls import reverse,reverse_lazy
from users.forms import CustomUserCreationForm
from django.views.decorators.csrf import csrf_protect
from .forms import UserUpdateForm,UpdateUserProfileForm
from django.contrib.auth.decorators import login_required 
from .models import Profile
from rest_framework.response import Response
from rest_framework.views import APIView
from .serializer import ProfileSerializer
from django.contrib.auth.models import User
import users.signals
@csrf_protect
def register(request):
    context = {}
    form = CustomUserCreationForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            user = form.save()
            login(request,user)
            return render(request,'home/index.html')
    context['form']=form
    return render(request,'registration/register.html',context)
@login_required
def profile(request):
    """[Profile]

    Args:
        request ([get]): [http method to retrieve data]
        id ([profile]): [retrieve specified user profile]

    Returns:
        [type]: [description]
    """
    prof = Profile.objects.all()
    return render(request,'profile/profile.html', {"profile": prof})


def edit_profile(request):
    
    user= request.user
    
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user.profile)
        profile = Profile.objects.get(user = request.user)
        prof_form = UpdateUserProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and prof_form.is_valid():
            user_form.save()
            prof_form.save()
            return redirect('users:profile')
    else:
        user_form = UserUpdateForm(instance=request.user)
        #profile = Profile.objects.get(user = request.user)
        prof_form = UpdateUserProfileForm(instance=request.user.profile)
    params = {
        'user_form': user_form,
        'prof_form': prof_form
    }
    return render(request, 'profile/edit_profile.html', params)



# Update it here



class ProfileList(APIView):
    def get(self,request,format = None):
        all_profile = Profile.objects.all()
        serializerdata = ProfileSerializer(all_profile,many = True)
        return Response(serializerdata.data)

users/templates/profile/edit_profile.html
{% extends 'base.html' %}
{%load bootstrap3%}
{%block content%}
<style>
    body {
    background-color: #c2c5aa;
    }
</style>
<body>
<div class="container" style="font-family: 'Jost', sans-serif; margin-bottom: 7rem;">
    <div class="row mt-5" style="padding-top: 80px;">
        <div class="col-sm-6 m-auto card">
            <br>
            <div>
                <form method="POST" enctype="multipart/form-data" class="p-5">
                    {%csrf_token%}
                    <fieldset class="form-group">
                        <legend class="border-bottom pt-4 mb-4">Profile info</legend>
                        {%bootstrap_form prof_form%}
                        {%bootstrap_form user_form%}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</body>
{%endblock%}

users/templates/profile/profile.html
    {%include 'base.html'%}
    {%block content%}
    <body style="background-color: white !important;">
    <div class="home-icon">
    <a href="{% url 'homepage:index' %}"><svg xmlns="http://www.w3.org/2000/svg" width="52" height="43" style="margin-left: 3rem; margin-top: 1rem;" fill="currentColor" class="bi bi-arrow-left-circle-fill" viewBox="0 0 16 16">
        <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0zm3.5 7.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/>
      </svg></a>
    </div>
    <div class="col-sm-6 m-auto " style="font-family: 'Jost', sans-serif;">
        <div class=" content-section container" style="padding-top: 100px;">
            <div class="media">
                <div class="col-sm-4">
                    <div style="width: 150px; height:150px; overflow:hidden; border-radius:50%" class="img-wrapper">
   
                        <img width="120%" height="120%" src="{{user.photo.url}}" alt="profile">
            
                    </div>
                </div>
                <div class="media-body">
                    <p class="text-secondary">{{user.profile.user_bio}}</p>
                    <h2 class="account-heading">{{user.username}}</h2>
                    <p class="text-secondary">{{user.email}}</p>
                   
                    <hr>

                    <a href="{% url  'users:edit_profile' %}">
                        <button class="btn btn-primary">Edit Profile</button>
                    </a>

                </div>
            </div>
        </div>
    </div>

</body>
    {%endblock%}
</div>