blog/urls.py
from django.urls import path,include,re_path
from . import views
app_name = "blog"
urlpatterns = [
    path("blogs", views.blogs, name="blogs"),
    path("add_blogs", views.add_blogs, name="add_blogs"),
    path('<slug:slug>/blog-comments', views.blog_comments, name="blog_comments"),
    #re_path(r'^join/', views.join, name='join'),
]

homepage/urls.py
from django.urls import path
from .views import PostCreateView,PostDetailView
from . import views
app_name = "homepage"
urlpatterns = [
    path("",views.index, name="index"),
    path('post/new/', PostCreateView.as_view(), name='new_post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('join_hood/<int:pk>/', views.joinHood, name='join_hood'),
    path('delete_post/<int:pk>/', views.deletePost, name='delete_post'),
    path('create_business/<int:pk>/', views.createBusiness, name='create_business')
    #path('post/<int:pk>/', views.detailView,name="post-detail"),
]

neighborhood/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("homepage.urls", namespace="homepage")),
    path("", include("users.urls", namespace="users")),
    path("", include("blog.urls", namespace="blog")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
]
##development media and static files settings
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, 
        document_root=settings.MEDIA_ROOT)
    
if settings.DEBUG:
    urlpatterns+= static(
    settings.STATIC_URL, 
    document_root = settings.STATIC_ROOT)   

users/urls.py
from django.urls import path,include,re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "users"   


urlpatterns = [
    path('api/profile',views.ProfileList.as_view()),
    path('profile/',views.profile,name = 'profile'),
    #path('user_profile/',views.user_profile,name = 'user_profile'),
    path('edit_profile/',views.edit_profile,name = 'edit_profile'), 
    path("/", views.register, name="register"),
    #path('profile/',views.profile,name = 'profile'),

    

]

homepage/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User 
from django.urls import reverse
from cloudinary.models import CloudinaryField
class Location(models.Model):
    name = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.name

class Post(models.Model):
    """
    Post model class to define post database table
    """
    name = models.CharField(max_length=400)
    location = models.ForeignKey('Location',null=True, on_delete=models.CASCADE)
      #image field
    image = CloudinaryField('image')
    #image = models.ImageField(upload_to='uploads/')
    description = models.CharField(max_length=100, blank=True)
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    occupants = models.ManyToManyField(User, related_name='occupants', blank=True)
    fire_department = models.IntegerField(null=True)
    hospital_contact = models.IntegerField(null=True)
    security_department = models.IntegerField(null=True)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('homepage:index')
    
    @property
    def number_of_comments(self):
        return Comment.objects.filter(post=self).count()

class Business(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150)
    neighborhood = models.ForeignKey(Post, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    created = models.DateTimeField(auto_now_add=True)
    phone = models.IntegerField()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.name 

homepage/forms.py
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User  
from .models import Business
class BusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ['name', 'email','phone']

homepage/views.py
from django.shortcuts import render,redirect
from .models import *
from .forms import *
from blog.models import BlogPost,Comment
from blog.forms import BlogPostForm
from django.views.generic import CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required 
# Create your views here.
def index(request):
    context = {
        'posts':Post.objects.all()
    }
    return render(request, "home/index.html", context)


class PostCreateView(LoginRequiredMixin, CreateView):
    """
    view class to create post
    """
    model = Post
    fields = "__all__"
    template_name = 'hoods/create_hood.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


@login_required(login_url='/accounts/login/')
def post(request, pk):
    """
    View to handle post model
    Args:
    Pk - Primary Key,an unique way to identify an object uniquely in relational database systems
    """

    post = Post.objects.get(pk=pk)
    user = request.user
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(author= user,description=form.cleaned_data["description"],post=post)
            comment.save()

    comments = Comment.objects.filter(post=post).order_by('-date_posted')
    context = {
        "post": post,
        "comments": comments,
        "form": form,
    }
   
    return self.get(self, request, pk, context)

class PostDetailView(DetailView):
    model = Post
    template_name = 'hoods/hood.html'
    context_object_name = 'post'

def joinHood(request,pk):
    hood =  Post.objects.get(id=pk)
    hood.occupants.add(request.user)
    occupants = hood.occupants.all()

    context = {
       'hood':hood,
       'occupants':occupants 
    }
    return render(request, 'hoods/hood.html', context)

@login_required(login_url='login')
def deletePost(request, pk):
    post = BlogPost.objects.get(id=pk)

    if request.user != post.author:
        return HttpResponse('You are not allowed')

    if request.method == 'POST':
        post.delete()
        return redirect('homepage:index')
    context = {

    }
    return render(request, 'hoods/delete.html', {'obj':post})


@login_required(login_url='login')
def createBusiness(request, pk):
    hood = Post.objects.get(id=pk)
    form = BusinessForm()
    user = request.user

    if request.method == 'POST':
        business = Business.objects.create (
            owner = user,
            neighborhood = hood,
            name = request.POST.get('name'),
            email= request.POST.get('email'),
            phone = request.POST.get('phone'),

        )
        return redirect('homepage:post-detail', pk=hood.id)     
    context = {
        'form':form,
        'hood': hood
    }
    return render(request, 'hoods/create_bussiness.html', context)

@login_required(login_url='login')
def search_profile(request):
    if 'search_user' in request.GET and request.GET['search_user']:
        name = request.GET.get("search_user")
        results = Profile.search_profile(name)
        print(results)
        message = f'name'
        params = {
            'results': results,
            'message': message
        }
        return render(request, 'results.html', params)
    else:
        message = "You haven't searched for any  category"
    return render(request, 'results.html', {'message': message})

homepage/templates/home/footer.html
    <div class="text-center p-3" style="color: red;">
      © 2022 Copyright:
      <a class="text-light" href="https://NeighborhoodWatch">Qwanzaneighborhood.com</a>
    </div>

homepage/templates/home/index.html
{% extends "base.html" %}
{% block content %}
<div class="navbar">
    {% include "home/navbar.html" %}
</div>

    <div id="main"></div>
    <!--NAVIGATION AREA ENDS-->
    <header>
     <center> <h1 style="color: #ffffcc;text-shadow: 0 0 5px #fff, 0 0 10px #fff, 0 0 20px green, 0 0 30px green,
      0 0 40px green, 0 0 55px green, 0 0 70px green;">QwanzaNeighborhood<i class="fas fa-search-location"></i></h1></center>
      <h6 style="
       color: white; font-size: 20px;">Learn on what is happening in your community and also make a report if there is any problem.</h6>
    </header>
    
    </div>
    
    <div class="container-fluid mt-5">
      <div class="px-lg-5">
        <div class="row">
          <!-- Gallery item -->
          {%for post in posts%}
          <div class="col-xl-3 col-lg-4 col-md-6 mb-4">
            
            <div class="bg-white rounded shadow-sm">
              <p style="margin: 0.5rem;" class="mr-2" href=""><i class="fas fa-house-user"></i>Neighbourhood: {{ post.name }}</p>
              <a href="/project/{{project.id}}">
                <img
                  src="{{ post.image.url }}"
                  alt=""
                  class="img-fluid card-img-top"
                />
              </a>
              <div class="p-4">
                <h5><a href="#" class="text-dark"> {{ post.description }}
                </p></a></h5>
                <p class="small text-muted mb-0"></p>
                
                  <a href="{% url 'homepage:post-detail' post.id %}">View your  Hood
                 </a></p>
               
                   <small style="opacity: 0.8; " class="white-important d-flex full-width flex-row-reverse">
                    Added on: {{ post.date_posted | date:"H:i l, d.m.y" }}
                 </small>
                <div
                  class="
                    d-flex
                    align-items-center
                    justify-content-between
                    rounded-pill
                    px-3
                    py-2
                    mt-4
                  "
                >
                  <p class="small mb-0">
                    <i class="fa fa-picture-o mr-2"></i
                    ><span class="font-weight-bold"> Area`s Location: {{post.location}}</span>
                  </p>
                  <div
                    class="badge badge-primary px-3 rounded-pill font-weight-normal"
                  ></div>
                  <div
                    class="badge badge-success px-3 rounded-pill font-weight-normal"
                  ></div>
                </div>
              </div>
            </div>
          </div>
          {%endfor%}
          <!-- End -->
        </div>
      </div>
    </div>
    



  
    <div class="footer">
        {% include "home/footer.html" %}
    </div>
  </body>


  



{% endblock %}

homepage/templates/home/navbar.html
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #E9967A;">
    <div class="container-fluid" style="background-color: #E9967A;">
      <a style="margin-left: 2rem;" class="navbar-brand" href="#">
       <!-- <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">-->
              <a class="navbar-brand" href="#" style="color: blue;">
            QwanzaNeighborhood<i class="fas fa-search-location"></i>Watch
              </a>
           
    </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#"></a>
          </li>
          <form class="d-flex" style="margin-left: 8rem;" action="">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-danger" type="submit">Search</i>
                <span class="visually-hidden"></span>
              </div></button>
          </form>
        </ul>
        
        <span class="navbar-text">
            <ul class="navbar-nav me-auto mwhiteb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'homepage:new_post' %}">Create  your Hood</i></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'users:profile' %}">Your Profile</a>
                </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</i></a>
</li> {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</i></a>
              </li>
              {% endif %}
               
                </li>
              </ul>
          
        </span>
      </div>
    </div>
  </nav>
  </a>